### ISSUE TITLE
[2.5] Seems to be fine!

### ISSUE THREAD

**Issue by nathanhornby** [brendo/field_metakeys#23]
Just a note that this extension seems to work fine on 2.5 - it at least:

- Installs
- Lets you add the field to entries
- Save multiple key/value pairs in an entry
- Output the key/value pairs as XML

I haven't personally run into any issues. I didn't want to be so bold as to bump the version myself just in case someone spots something that needs updating.

**Comment by animaux** [comment]
Thanks @nathanhornby, anyone else tried this in 2.5/2.6? I guess I should go for `integration` then? @brendo

**Comment by jurajkapsz** [comment]
Works good on 2.5 / 2.6 .
